### ISSUE TITLE
Update module is not working due to Content Security Policy

### ISSUE THREAD

**Issue by theus** [theus/instantgram#10]
![image](https://user-images.githubusercontent.com/61322/47753485-78753900-dc76-11e8-9a05-1f41506124b6.png)

Instagram changed recently the [Content Security Policy](https://developers.google.com/web/fundamentals/security/csp/) header settings to their "secure domains". Now, [instantgram] can't search for an update because this module uses a request to [instantgram] page in Github to get the last version of himself.

[instantgram] can't advise users a new update, difficulting for the users. For while, [instantgram] is working but future fix versions are compromised (or at least will be harder to user find an update)

_PS: In theory, [CSP](https://developers.google.com/web/fundamentals/security/csp/) can disable `unsafe-inline` and `unsafe-eval` but I don't know what this can change [instantgram] work, because, in theory, it uses an inline script directly in `console` by a bookmarklet._

**Comment by M1kep** [comment]
Have you looked into possibly converting it to a TamperMonkey script? This _in theory_ could allow you to have a button on the screen to trigger the code and I believe tampermonkey/greasemonkey has an update directive that it use

**Comment by theus** [comment]
@M1kep it's an idea! I'll look at this possibility.

**Comment by theus** [comment]
Update module will be removed in [v4.0.0](https://github.com/theus/instantgram/milestone/4)
