### ISSUE TITLE
Is Instagram banning accounts for using this?

### ISSUE THREAD

**Issue by Coldblackice** [theus/instantgram#15]
I've seen two accounts recently banned out of the blue, no other actions/posts/messaging/etc. done with the accounts. One of them was even newly created (from new IP, email), before getting a notification days later that the account was disabled for TOS violation.

The only thing I can surmise is that Instagram is detecting use of this script, watching for if/when an account accesses a photo resource (i.e. high-def) that it otherwise shouldn't be able to access, at least directly.

Could this be what's happening?

**Comment by theus** [comment]
I think that is improbable. The script executes a simple parser to get the image source and removes a crop param of the image's URL to get the high-def photo. 

In theory, for Instagram, is the same as view image in the Instagram web.

**Comment by Coldblackice** [comment]
@theus I'm not disputing you, but the third I had to create after the previous two accounts were banned is still going strong, no ban, and it's been a month now. I've been careful to never use Instantgram while I'm logged into the account. It could definitely be just a coincidence, but I just don't know what else two prior account bannings, back-to-back, would be for, as there was really nothing much being done with the accounts, especially the second account made after the first ban.

I also had thought it would be totally improbable, thinking it would just look like normal media loading to Instagram.

> 
> 
> I think that is improbable. The script executes a simple parser to get the image source and removes a crop param of the image's URL to get the high-def photo.
> 
> In theory, for Instagram, is the same as view image in the Instagram web.

But I wonder if this is what may be causing it: does the script grab a higher-res photo, or is it the same image that gets served by default on a normal photo viewing? I assume it's the same image. Which brings me to the next question: is it possible that Instagram is seeing this media being accessed without the appropriate "context" that it would normally, like seeing that there was no "Referrer" parameter on the request, or that X/Y/Z scripts weren't run immediately preceding the image grab or after?

**Comment by theus** [comment]
As I said, @Coldblackice, is improbable. But I will let this issue open to verify if this happens with other users, ok?

**Comment by Coldblackice** [comment]
> As I said, @Coldblackice, is improbable. But I will let this issue open to verify if this happens with other users, ok?

Sounds good, thank you. I can test this, as well, creating a new test account to see if it happens. If no one else has this issue, then it must be something on my end.

**Comment by theus** [comment]
Closing this issue again

**Comment by UnixCro** [comment]
Is instantgram currently downloading the best possible quality?

> The script executes a simple parser to get the image source and removes a crop param of the image's URL to get the high-def photo.

**Comment by theus** [comment]
@UnixCro not always. Sometimes the Instagram loads only the "medium" quality and is that the [Instantgram] opens.
