### ISSUE TITLE
Instantgram 3.0.1 doesn't get the highest image/video resolution 

### ISSUE THREAD

**Issue by ghost** [theus/instantgram#16]
I recently noticed that Instantgram 3.0.1 doesn't get the highest possible resolution when getting images and videos. I noticed that when I was using the website https://deskgram.net/ the images and videos were very clear, so I compared them with the images and videos Instantgram gets and noticed that the resolutions were significantly higher on Deskgram. Here are some examples:

Image:
Instantgram (Resolution: **1080x1350**): https://www.instagram.com/p/Bz6FKcxgTpp/
Deskgram (Resolution: **1440x1800**): https://deskgram.net/p/2088004085562292841_25025320

Video:
Instantgram (Resolution: **480x600**): https://www.instagram.com/p/Bz3hiBfg4iK/
Deskgram (Resolution **720x900**): https://deskgram.net/p/2087284425909045386_25025320

IGTV:
Instantgram (Resolution: **480x852**): https://www.instagram.com/p/Bz3bsXoAU_V/
Deskgram (Resolution: **720x1280**): https://deskgram.net/p/2087258748589526997_25025320

I don't know how Deskgram gets the videos and images in such high resolutions, but I thought you'd like to know about it.

**Comment by theus** [comment]
Hi @ULBAZOR, 

Basically, I use a simple regex at image URL to identify and remove crop params based in a pattern that I already know. The question is: sometimes, without these params, the URL of the image becomes invalid. So, by security, I stopped trying to find the max resolution because I don't test if an image is valid or not.

**Comment by ameer1234567890** [comment]
Checking if image is valid or not, is not feasible for instantgram, since it would introduce some lag.

**Comment by saschaheim** [comment]
Deskgram not working anymore.
So it is not possible for any research development sorry.

**Comment by fyhtma** [comment]
@ThinkBIG-Company you can use insta-stories.com or zasasa.com/en/download_instagram_videos_or_photos.php instead of deskgram

**Comment by saschaheim** [comment]
Ok will try that thanks for your reply

**Comment by saschaheim** [comment]
Have tried your suggestions and compared with my work and cannot see any higher resolutions.
So at now there isnt any better solution without upscaling the image/video.
