### ISSUE TITLE
Only the first photo in a set can be downloaded as of today

### ISSUE THREAD

**Issue by Orudeon** [theus/instantgram#17]
Topic.
I'm on chrome 75.0.3770.142 in the United States using Instantgram 3.0.1
Example post: https://www.instagram.com/p/Bzw1fF5Fd7W/

**Comment by Orudeon** [comment]
Started working again soooooo who knows. I'll keep an eye on it.

**Comment by theus** [comment]
Hi @Orudeon, 

Instagram can change some part of their code structure at any time, so, is very sensible. Some features could be broken :(

But thanks for your issue!
