### ISSUE TITLE
How to Use on Android Chrome

### ISSUE THREAD

**Issue by daprofessa19** [theus/instantgram#18]
Hi,

Does anyone know how to use this bookmarklet on Android (Chrome or Firefox). I saved the bookmarklet, but nothing happens when opening the bookmark when browsing an Instagram page.

Thanks

**Comment by theus** [comment]
Hi @daprofessa19, 

I think that is not possible. I don't know if the bookmark system of mobile browsers can run javascript, but, even if possible, the structure of Instagram Mobile can be different, so, the bookmarklet wouldn't work properly.

**Comment by UnixCro** [comment]
Any ideas how it is possible to run instantgram on iOS and Android?

**Comment by Wag669** [comment]
> 
> 
> Any ideas how it is possible to run instantgram on iOS and Android?



The script is way too long for the ios bookmarks 
I tried syncing with iOS Chrome and iOS FireFox, but the bookmarks do not appear 
I also tried copying the script sending it by email and then pasting it to an existing bookmark, but the system just cuts part of the script and it doesn't work.
