### ISSUE TITLE
Not working for IG carousel

### ISSUE THREAD

**Issue by shimmyD99** [theus/instantgram#21]
Keep receiving error message when trying to use for carousel: "Ops, did you open any Instagram post? Like for example instagram.com/p/82jd828jd"

Works fine for single images still. Thanks, love the bookmarklet it's so handy

**Comment by theus** [comment]
Thanks @shimmyD99. 

I think that carousel don't work only when has a video with images. When the carousel has only images, [instantgram] works fine. 

This link with 2 images works with yours? https://www.instagram.com/p/B7WFNHiluQA/

**Comment by paulogliwa** [comment]
I have the same problem but only in Incognito Mode (Firefox).

**Comment by theus** [comment]
> I have the same problem but only in Incognito Mode (Firefox).

This is new... 🤔

**Comment by shimmyD99** [comment]
I still get the same error code with the link you pasted above. Video or otherwise, it doesn't seem to be working

**Comment by JohnPlanetary** [comment]
I did start receiving that error "Ops, did you open any Instagram post? Like for example instagram.com/p/82jd828jd" today in both Mozilla Firefox 74.0 x64 and in the Google Chrome 80.0.3987.132 x64, using [instantgram 3.0.1], both from Portugal and even from USA (these last one using VPN) Internet connections.
It is happening for example in: https://www.instagram.com/p/B9R2RPajUYV/ or any other that have more than one image in the same post.
I'm attaching the full page (html, js, jpg, png, css): 
[Example.zip](https://github.com/theus/instantgram/files/4331490/Example.zip), that I downloaded in the hope it helps find the problem.

**Comment by Wag669** [comment]
Started receiving this message sometime yesterday.
Single pictures work, but with "carousel" the error "Ops, did you open any Instagram post? Like for example instagram.com/p/82jd828jd" keeps occurring on all browsers that I use (mozila, chrome, safari, mobile safari)

**Comment by Orudeon** [comment]
Also getting this issue with carousel posts in Firefox 74 in the united states region.

**Comment by enrbriones** [comment]
I get the same message in Edge, Chrome and Opera, when there are carrousel images.

**Comment by theus** [comment]
I think that Instagram has rollout the changes to everyone. I already identified what has changed but I don't know how to fix yet. I'm just getting it the first one of a gallery.

**Comment by theus** [comment]
Can you guys try this version of the bookmark? http://jsfiddle.net/theus/hnvd6w4j/1/embedded/result/

A point that I have noted is that the last image of a gallery isn't working.

**Comment by Orudeon** [comment]
That bookmark works for me in Firefox 74 U.S. region (except that it can only get up to the second-to-last image as you noted).

It still 'prefers' to grab videos that are up to two photos or so away but I think we've been over how difficult that is to fix already.

**Comment by Wag669** [comment]
> 
> 
> Can you guys try this version of the bookmark? http://jsfiddle.net/theus/hnvd6w4j/1/embedded/result/
> 
> A point that I have noted is that the last image of a gallery isn't working.

On firefox and chrome
Doesn't get the last picture in the gallery

**Comment by theus** [comment]
Now, seems that only the gallery with 2 photos doesn't work (getting only the second). Can you test? http://jsfiddle.net/theus/hnvd6w4j/2/embedded/result/

**Comment by Orudeon** [comment]
Works fine on a four-image carousel.

Works fine on a ten-image carousel.

Can confirm that I'm also only getting the second image in a two-image carousel.

**Comment by Wag669** [comment]
> 
> 
> Now, seems that only the gallery with 2 photos doesn't work (getting only the second). Can you test? http://jsfiddle.net/theus/hnvd6w4j/2/embedded/result/

Works on desktop versions of firefox and chrome and iPad version of safari
Doesn't work on Safari for iPhone :(

Errors on all pictures of carousel, except the last one

**Comment by theus** [comment]
Thank you guys for the testing. And now, should I release a version with this bug? At least, the bookmarklet can grab galleries except with only 2 images (I hope).

**Comment by Orudeon** [comment]
Right now I have both test bookmarks saved because at least then it grabs both. It's a very bizarre bug.

**Comment by mads2** [comment]
> Now, seems that only the gallery with 2 photos doesn't work (getting only the second). Can you test? http://jsfiddle.net/theus/hnvd6w4j/2/embedded/result/

Worked flawlessly now in all my  tests with both video and pictures only carousel. Couldn't find a post with them mixed though.
(Ubuntu 18, Chrome 79.0.3945.130 (Official Build) (64-bit))

**Comment by reven** [comment]
I've tested this last version with a post that contains one image and one video and it only downloads the video. Don't know if it's a part of the same issue or a completely different one?
Edit: Ok, I see that this may be more related to issue #9

**Comment by ameer1234567890** [comment]
> Now, seems that only the gallery with 2 photos doesn't work (getting only the second). Can you test? http://jsfiddle.net/theus/hnvd6w4j/2/embedded/result/

I was also having the issue with image carousels. This version works but only gets the first image.

**Comment by KarlB22** [comment]
This new version works for me but on a two image im also only getting the first image.

**Comment by Orudeon** [comment]
All three versions of the bookmarklet stopped grabbing story images today (3.0.1, 12qq3ua, and 9xzn1ish). Videos work fine, posts work fine. 12qq3ua still only grabs the first image out of two, 9xzn1ish still only grabs the second image out of two

**Comment by theus** [comment]
> All three versions of the bookmarklet stopped grabbing story images today

Here, 3.0.1 works fine with story images yet. 

I don't know what to do with albums. I've thought about when [instantgram] not sure about the image, show a modal with thumbnails for the user to intervene. 🤔

**Comment by saschaheim** [comment]
I have made a new repository because of lack of frequently updates here.
https://github.com/ThinkBIG-Company/instantgram
And the new bookmark site:
https://thinkbig-company.github.io/instantgram/

All issues are fixed and multiple videos images in single post are fully supported!
Happy testing issues are welcome

**Comment by theus** [comment]
@ThinkBIG-Company awesome work! I tested here and seems work perfectly :heart_eyes:
