### ISSUE TITLE
InstantGram doesn't work anymore on most images

### ISSUE THREAD

**Issue by kettenfett** [theus/instantgram#23]
Instagram must have changed something. I'm getting this on almost all images since yesterday:

![grafik](https://user-images.githubusercontent.com/23098362/76698830-8f6bce00-66a7-11ea-9a12-9fd5a527e1fc.png)

**Comment by Wag669** [comment]
Instantgram not working with "carousel" posts, is already reported 

[https://github.com/theus/instantgram/issues/21](url)

**Comment by Wag669** [comment]
Instantgram not working with "carousel" posts, is already reported

**Look for:** _Not working for IG carousel #21_ in [https://github.com/theus/instantgram/issues](url)

**Comment by philippHRO** [comment]
it's not just on the carousel
![grafik](https://user-images.githubusercontent.com/23098362/76703328-63fdd900-66d1-11ea-8c1f-799810ad214f.png)

**Comment by theus** [comment]
Duplicates #21.
