### ISSUE TITLE
3.0.1 Not detecting Instagram posts.

### ISSUE THREAD

**Issue by KarlB22** [theus/instantgram#27]
When I try to use it on instagram posts on my feed or on someone's profile i get a message saying "Ops, did you open any Instagram post? Like for example instagram.com/p/82jd828jd"

It appears to work fine on instagram stories still though.

**Comment by KarlB22** [comment]
This appears to be a duplicate as it won't work on carousel images.

**Comment by theus** [comment]
Duplicate #21
