### ISSUE TITLE
Not working on posts with more than 1 picture and video in it

### ISSUE THREAD

**Issue by Zackqalwashere** [theus/instantgram#28]

**Comment by GOLDIdeluxe** [comment]
would be awesome if it would work again as it worked in the past.

**Comment by Erdloch** [comment]
It would be great if someone could fix this! THANK YOU!

**Comment by seanorama** [comment]
This is the error from Firefox console:
```
searchImageOnScreen() [instantgram] 3.0.1 TypeError: can't access property "children", p is null
(function(){;!function(e){var t={};function n(a){if(t[a])return t[a].exports;var r=t[a]={i:a,l:!1,exports:{}};return e[a].call(r.exports,r,r.exports,n),r.l=!0,r.exports}n.m=e,n.c=t,n.d=function(e,t,a){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:a})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var a=Object.create(null);if(n.r(a),Object.defineProperty(a,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var r in e)n.d(a,r,function(t){return e[t]}.bind(null,r));return a},n.n=function(e){var t=e&&e.__esModule:1:13944
    NextJS 6
```

**Comment by kafene** [comment]
Here's my temporary replacement

```javascript
javascript:(function(){
    var imgs = [...document.images].
        filter(i => !!i.srcset).
        filter(i => /scontent/.test(i.src)).
        map(i => ({h: getComputedStyle(i).height, i})).
        filter(o => parseInt(o.h) > 300).
        map(o => o.i.src);
    console.log(imgs.join("\n"));
    imgs.forEach(img => window.open(img));
})();
```

You can create a bookmark with that as the URL and use it. No guarantee it will work for very long.

Note - that opens every image found for multi-image posts. You might have to allow popups from instagram.com for it to open them all, if it only opens the first one that means the rest are being blocked as popups. Instagram doesn't have popup ads so I don't worry about allowing them.

Edit - okay this isn't perfect. It seems instagram does some funky stuff when scrolling through images and if there are more than 2 or 3 they don't all exist in the DOM, only the first and next image exist, or if you've started scrolling through, the previous, current and next. This will open all the ones that exist in the DOM, but it's not so convenient as I thought from looking at posts with only 1-2 images.

**Comment by saschaheim** [comment]
I have made a new repository because of lack of frequently updates here.
https://github.com/ThinkBIG-Company/instantgram
And the new bookmark site:
https://thinkbig-company.github.io/instantgram/

All issues are fixed and multiple videos images in single post are fully supported!
Happy testing issues are welcome

**Comment by GOLDIdeluxe** [comment]
thank you very much, so far it works perfect!
