### ISSUE TITLE
Have fixed all Issues and will share my work with you in the next few hours.

### ISSUE THREAD

**Issue by saschaheim** [theus/instantgram#29]

**Comment by saschaheim** [comment]
I have made a new repository because of lack of frequently updates here.
https://github.com/ThinkBIG-Company/instantgram
And the new bookmark site:
https://thinkbig-company.github.io/instantgram/

Happy testing issues are welcome

**Comment by theus** [comment]
Awesome @ThinkBIG-Company!

Can you open a PR for we release?

**Comment by saschaheim** [comment]
Yes

**Comment by theus** [comment]
PR #30
