### ISSUE TITLE
Problem in running this in edge

### ISSUE THREAD

**Issue by thecloakmaster** [theus/instantgram#31]
Well when this used to work some time back in the new Microsoft Edge browser. I usually use Mozilla Firefox but I have my account logged in and today when I tried using it, it doesn't open the new tab like it should.

**Comment by theus** [comment]
Did it work?

**Comment by thecloakmaster** [comment]
Yes. I think there was a problem with my login. So I signed out and logged in back and it works now. Thanks :)
