### ISSUE TITLE
set language: undefined

### ISSUE THREAD

**Issue by hanskokx** [theus/instantgram#32]
When I try to use the bookmarklet, instead of getting the image as expected, I receive the following notification in the web console:

```
[instantgram] set language: undefined 
 For more information about available languages please check http://theus.github.io/instantgram
```

However, there doesn't appear to be any documentation around this (unless I am blind?)

**Comment by theus** [comment]
Hi @skipmeister123, thanks for your issue!

How the language of your browser?

**Comment by hanskokx** [comment]
en-US

**Comment by theus** [comment]
Is weird because en-US is defined as default even if [instantgram] doesn't have a translation for the specific language. 

Which browser and [instantgram] version are you using?

**Comment by hanskokx** [comment]
Edge chromium, 4.0.0

**Comment by theus** [comment]
@skipmeister123 can you test this version https://peach-acoustic-octopus.glitch.me/?

**Comment by hanskokx** [comment]
It set the language properly to en-US, but didn't give me the image. I thought maybe there was an extension causing problems, so I opened a private browsing window and tried there - with the same results.

What I'm seeing is that this test returns false.

                            if (e.regexStoriesURI.test(e.path)) {
I poked around for a while in the JavaScript, but your obfuscator makes it really annoying to figure out what is what, so I gave up.
