### ISSUE TITLE
URL Signature Mismatch on Edge Chromium

### ISSUE THREAD

**Issue by Lumi-sg** [theus/instantgram#33]
Hi there, pretty self explanatory problem.

I get that error on Edge Chromium, but not on firefox for some reason.

**Comment by victorbblanco** [comment]
Exactly, me too.

**Comment by theus** [comment]
Can you guys test this version and let me know if it works? https://jsfiddle.net/theus/rk27as1q/1/show

**Comment by Lumi-sg** [comment]
Hi there,

it seems to work again so thanks! but it's not downloading the highest quality / largest image possible.

**Comment by theus** [comment]
> it seems to work again so thanks! but it's not downloading the highest quality / largest image possible.

It was implemented if the [instagram] doesn't get the highest quality image, so brings the normal one. Sometimes it can't find.

**Comment by theus** [comment]
So, can I release this version? Is that all alright?

**Comment by stalker0912** [comment]
4.0.1 seems to fix this problem. I'd say release it.

**Comment by theus** [comment]
@stalker0912 alright. I'll release it.

**Comment by dantewang** [comment]
@theus This seems to be happening again with latest Edge.

Edge version: 92.0.902.73
Example post: any post, or https://www.instagram.com/p/CShBIgWrMUV/
