### ISSUE TITLE
Cannot download story with new story layout

### ISSUE THREAD

**Issue by ale-carra** [theus/instantgram#35]
Yesterday I got a new story UI. Ever since then, if I run instantgram I get the following error in console

[instantgram] set language: undefined 
 For more information about available languages please check http://theus.github.io/instantgram

This is a screenshot of the new UI
![Captura de pantalla -2020-12-08 00-23-40](https://user-images.githubusercontent.com/1590688/101560890-074ef680-39a3-11eb-862f-62e50e72439a.png)

**Comment by theus** [comment]
I did not receive the new UI yet :(

**Comment by theus** [comment]
Hey, can you check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
