### ISSUE TITLE
Videos in posts don't work 

### ISSUE THREAD

**Issue by Wag669** [theus/instantgram#36]
Hello!

I would like to report an issue

For the past few hours the bookmarklet stopped getting videos from posts 
It does nothing if I open a post that includes a video 
If I use the applet in my feed I receive the following error:

_If you're trying open a video, try enter on Instagram post page. Like for example instagram.com/p/82jd828jd. If you're already in it, try refreshing the page before running [instantgram] or open the post in a new tab. (this proccess is neccessary only for videos)_

I tried the 4.0.1 beta version and it just doesn't do a thing

Thank you in advance
_:)_

**Comment by runchbox** [comment]
It has been a little longer than two days for me, but same thing.  Refreshing, new page..none of it works.
Wasn't working in Firefox 83 or 84.
Thanks for the work.

**Comment by ale-carra** [comment]
Looks like it's because Instagram is using blob urls in videos. I've been having issues with stories as well

**Comment by theus** [comment]
These blob problems are already known (https://github.com/theus/instantgram/issues/22). But I'll try something to resolve this.

**Comment by Wag669** [comment]
Tried the 6.0.0 version
Skipped a couple of beats when the page turned dark and the popup appeared 
But it works :)

**Comment by ale-carra** [comment]
> Tried the 6.0.0 version
> Skipped a couple of beats when the page turned dark and the popup appeared
> But it works :)

Where is version 6.0.0?

**Comment by Wag669** [comment]
> 
> 
> > Tried the 6.0.0 version
> > Skipped a couple of beats when the page turned dark and the popup appeared
> > But it works :)
> 
> Where is version 6.0.0?

On the Bookmarklet page

[REDACTED]

**Comment by theus** [comment]
At the moment, the official bookmarklet doesn't have a fix to this. When I release it, I'll close this issue and notify you here.

**Comment by theus** [comment]
Hello 👋

Can you guys test this version of bookmarklet? It's supposed to resolve the blob issue https://solid-valuable-ox.glitch.me/.

Please, give me feedback. Thanks.

**Comment by MexTrx** [comment]
Found that this version solved the video issue. Could not find any other bugs.

**Comment by theus** [comment]
@MexTrx thanks for feedback. I'll release it.

**Comment by runchbox** [comment]
Working for me now!

> 
> 
> Hello wave
> 
> Can you guys test this version of bookmarklet? It's supposed to resolve the blob issue https://solid-valuable-ox.glitch.me/.
> 
> Please, give me feedback. Thanks.
