### ISSUE TITLE
Stories get cropped and became images now

### ISSUE THREAD

**Issue by reigun999** [theus/instantgram#38]

**Comment by saschaheim** [comment]
Hello version 6 is on the way with blob video support and many other improvements.
Also, the updater checker is coming back.
It adresses all the issues.
So stay tuned.
[REDACTED]
Love Sascha

**Comment by theus** [comment]
@reigun999 Can you explain more?

**Comment by Erdloch** [comment]
I think I have the same issue. The most stories get cropped now, also with the latest version 4.0.3
This happens to most new and also older stories, but not to all - some stories are still okay.
At least in my case, videos are never affected - they always get displayed correctly, I only have these problems with images.

Example: When you go to https://www.instagram.com/eminem/ and open the first story "MERCH", you see this picture:
![original](https://user-images.githubusercontent.com/49982211/104183427-3decb680-5412-11eb-9364-0d942305aab5.jpg)

When I click on the Instantgram bookmark in Firefox 84.0.2, I get a cropped image only:
![Cropped](https://user-images.githubusercontent.com/49982211/104183457-45ac5b00-5412-11eb-869a-3e7c95f8fe9b.jpg)

**Comment by theus** [comment]
I repeated the process and [instantgram] gave me [this link](https://instagram.fssa3-1.fna.fbcdn.net/v/t51.12442-15/e35/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fssa3-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=c7HXViHgjZYAX_xii9c&tp=1&oh=fd647d5bf2ec800f5a79cb3c68b9b6fa&oe=60091C93&ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2). Can you send me the direct link to the image?

The image loaded correctly: 
![image](https://user-images.githubusercontent.com/61322/105030500-a64f1f80-5a32-11eb-94b7-feb7a920a785.png)

**Comment by Wag669** [comment]
> I think I have the same issue. The most stories get cropped now, also with the latest version 4.0.3

Please ignore this post, I was wrong

**Comment by Erdloch** [comment]
Thanks for this hint, I seems like I was using the old version from https://theus.github.io/instantgram/
It's working now! Thank you!

**Comment by theus** [comment]
No, the [instantgram] was created by me and this is the only official version. The [instantgram] that you say is an unofficial version.

**Comment by theus** [comment]
I'm removing their link references because is not cool send a link to an unofficial version in the original version

**Comment by Wag669** [comment]
> 
> 
> I'm removing their link references because is not cool send a link to an unofficial version in the original version

Wait.... 
What??? 
I'm confused.... 

I thought that was **your** bookmarklet 
_Terribly sorry for the inconvenience caused by my post_

**Comment by theus** [comment]
@Wag669 no problem :sweat_smile:. The confusion was not actually caused by you :man_shrugging:

**Comment by theus** [comment]
@Wag669 by the way, in [instantgram 4.0.3] works as well with stories (don't crop?)

**Comment by Erdloch** [comment]
So on my Firefox 84.0.2, theus version 4.0.3 crops the image - see the following Link: https://instagram.flnz1-1.fna.fbcdn.net/v/t51.12442-15/e35/c0.420.1080.1080a/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.flnz1-1.fna.fbcdn.net&_nc_cat=108&_nc_ohc=c7HXViHgjZYAX_ULuf1&tp=1&oh=1823f851dca1c1f83b3771eee4c4a177&oe=6008E670&ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2

With the (fork?) from ThinkBIG-Company - Version 6.0.0, it doesn't get cropped.

**Comment by Wag669** [comment]
> 
> 
> @Wag669 by the way, in [instantgram 4.0.3] works as well with stories (don't crop?)


all stories on Eminem's account, under **_Merch_**, are cropped

**Comment by theus** [comment]
Please, can you test with this "develop" bookmarklet? https://adaptable-lucky-shrew.glitch.me/

Instructions:

![recording (3)](https://user-images.githubusercontent.com/61322/105066072-5a65a000-5a5d-11eb-9e6f-e759772d4eda.gif)

Send me this _outerHTML_

![image](https://user-images.githubusercontent.com/61322/105066647-c6480880-5a5d-11eb-860e-fe7c60b8ed86.png)

**Comment by Wag669** [comment]
outerHTML 

`<img class="y-yJ5 i1HvM " decoding="sync" sizes="502.1875px" srcset="https://instagram.fath5-1.fna.fbcdn.net/v/t51.12442-15/e35/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&amp;_nc_cat=108&amp;_nc_ohc=c7HXViHgjZYAX9XHefU&amp;tp=1&amp;oh=f1d78db9792afc9681c8e9338870a108&amp;oe=60091C93&amp;ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2 1080w,https://instagram.fath5-1.fna.fbcdn.net/v/t51.12442-15/sh0.08/e35/p750x750/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&amp;_nc_cat=108&amp;_nc_ohc=c7HXViHgjZYAX9XHefU&amp;tp=1&amp;oh=99b3dc52846d4f0010027084b3418199&amp;oe=600999B6&amp;ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2 750w,https://instagram.fath5-1.fna.fbcdn.net/v/t51.12442-15/sh0.08/e35/p640x640/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&amp;_nc_cat=108&amp;_nc_ohc=c7HXViHgjZYAX9XHefU&amp;tp=1&amp;oh=780bd016ee8b393afe4137eff207d5c4&amp;oe=600936B6&amp;ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2 640w,https://instagram.fath5-1.fna.fbcdn.net/v/t51.12442-15/e35/p480x480/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&amp;_nc_cat=108&amp;_nc_ohc=c7HXViHgjZYAX9XHefU&amp;tp=1&amp;oh=0476e9b104eb9cfab03076df20db7909&amp;oe=6009A6EB&amp;ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2 480w,https://instagram.fath5-1.fna.fbcdn.net/v/t51.12442-15/e35/p320x320/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&amp;_nc_cat=108&amp;_nc_ohc=c7HXViHgjZYAX9XHefU&amp;tp=1&amp;oh=649a2e8a90e53de88c2afeb36cdc7bf9&amp;oe=60095371&amp;ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2 320w,https://instagram.fath5-1.fna.fbcdn.net/v/t51.12442-15/e35/p240x240/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&amp;_nc_cat=108&amp;_nc_ohc=c7HXViHgjZYAX9XHefU&amp;tp=1&amp;oh=706c1fcdfb7384f532b571a57096608f&amp;oe=600924CB&amp;ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2 240w" src="https://instagram.fath5-1.fna.fbcdn.net/v/t51.12442-15/e35/37741793_510219166083656_8179067734017966080_n.jpg?_nc_ht=instagram.fath5-1.fna.fbcdn.net&amp;_nc_cat=108&amp;_nc_ohc=c7HXViHgjZYAX9XHefU&amp;tp=1&amp;oh=f1d78db9792afc9681c8e9338870a108&amp;oe=60091C93&amp;ig_cache_key=MTg0MDEzOTUyMTU3NDA1NzU3Mw%3D%3D.2">`

**Comment by Erdloch** [comment]
I think it is a Firefox issue.
I have just tried your version 4.0.3 in Chrome, and everything is fine. It only gets cropped in Firefox.
And I saw you have debugged it in Chrome ;-)

**Comment by theus** [comment]
Alright, I'll look at how is working in Firefox :thinking:

**Comment by mlunax** [comment]
Firefox has still issue.
Caching I think cuz when I directly take the URL out of inspector mode to the other browser I still have cropped.

**Comment by theus** [comment]
The new version should be working https://theus.github.io/instantgram/
