### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by UnixCro** [theus/instantgram#39]
Otherwise great work!

**Comment by theus** [comment]
Which error is thrown on Safari?

**Comment by UnixCro** [comment]
There is no error message, it just doesn't load.
Instead of having a horizontal reading bar as in Chrome, in Safari the reading list is one below the other and vertical.
When I go to a picture in Safari on "instagram.com" the same page opens again with this link:

(Edit: It occurs to me that the Instantgram wants it to be dragged into the favorites bar. However, I am not aware of any possibility to push this program into there. In Safari the favorites are different than in Chrome, they only appear when you open a new tab)

`"javascript: (function ()% 7B;! function (e)% 7Bvar% 20t =% 7B% 7D; function% 20n (a)% 7Bif (t% 5Ba% 5D) return% 20t% 5Ba% 5D.exports; var% 20r = t% 5Ba% 5D =% 7Bi: a, l:! 1, exports:% 7B% 7D% 7D; return% 20e% 5Ba% 5D.call (r.exports, r, r.exports, n ), rl =! 0, r.exports% 7Dn.m = e, nc = t, nd = function (e, t, a)% 7Bn.o (e, t)% 7C% 7CObject.defineProperty (e, t ,% 7Benumerable:! 0, get: a% 7D)% 7D, nr = function (e)% 7B% 22undefined% 22! = Typeof% 20Symbol && Symbol.toStringTag && Object.defineProperty (e, Symbol.toStringTag,% 7Bvalue:% 22Module% 22% 7D), Object.defineProperty (e,% 22__esModule% 22,% 7Bvalue:! 0% 7D)% 7D, nt = function (e, t)% 7Bif (1 & t && (e = n (e)), 8 & t) return% 20e; if (4 & t &&% 22object% 22 == typeof% 20e && e && e .__ esModule) return% 20e; var% 20a = Object.create (null); if (no (a), Object.defineProperty (a,% 22default% 22,% 7Benumerable:! 0, value: e% 7D), 2 & t &&% 22string% 22! = Typeof% 20e) for (var% 20r% 20in% 20e) nd (a, r, function (t)% 7Breturn% 20e % 5Bt% 5D% 7D.bind (null, r)); return% 20a% 7D, nn = function (e)% 7Bvar% 20t = e && e .__ esModule? Function ()% 7Breturn% 20e.default% 7D: function ( )% 7Breturn% 20e% 7D; return% 20n.d (t,% 22a% 22, t ), t% 7D, no = function (e, t)% 7Breturn% 20Object.prototype.hasOwnProperty.call (e, t)% 7D, np =% 22% 22, n (ns = 3)% 7D (% 5Bfunction (e, t, n)% 7B% 22use% 20strict% 22; Object.defineProperty (t,% 22__esModule% 22,% 7Bvalue:! 0% 7D), t.default = function (e, t)% 7Bt = t % 7C% 7Cwindow% 7C% 7Cdocument.documentElement; var% 20n = e.getBoundingClientRect (); return% 20n.bottom% 3E0 && n.right% 3E0 && n.left% 3C (t.innerWidth% 7C% 7Ct.clientWidth) && n.top % 3C (t.innerHeight% 7C% 7Ct.clientHeight)% 7D% 7D, function (e, t, n)% 7B% 22use% 20strict% 22; Object.defineProperty (t,% 22__esModule% 22,% 7Bvalue :! 0% 7D), t.default = function (e)% 7Bvar% 20t =% 5B% 5D; t.push (e); for (; e.parentNode;) t.unshift (e.parentNode), e = e .parentNode; return% 20t% 7D% 7D, function (e, t, n)% 7B% 22use% 20strict% 22; Object.defineProperty (t,% 22__esModule% 22,% 7Bvalue:! 0% 7D), t. default = function (e, t, n)% 7Bfor (var% 20a = 0; a% 3Ce.length; a ++) t.call (n, a, e% 5Ba% 5D)% 7D% 7D, function (e, t, n)% 7B% 22use% 20strict% 22; var% 20a = f (n (4)), r = f (n (2)), o = f (n (0)), i = f (n (6)), s = f (n (7)), l = f (n (8)), d = f (n (9)), u = f (n (10)), c = f (n (11)), g = f (n (14)), m = f (n (15)); function % 20f (e)% 7Breturn% 20e && e .__ esModule? E:% 7B% 22default% 22: e% 7D% 7Dvar% 20p =% 7Bcover: 'img% 5Bstyle =% 22object-fit:% 20cover;% 22% 5D' , srcset:% 22img% 5Bsrcset% 5D% 22, img:% 22img% 22% 7D, h =% 7BVERSION:% 224.0.3% 22, mediaImageElExpressions: p, mediaImageElExpression: window.navigator.userAgent.indexOf (% 22Edge% 22)% 3E-1% 7C% 7Cwindow.navigator.userAgent.indexOf (% 22Edg% 22)% 3E-1? P.cover: p.srcset, hostname: window.location.hostname, path: window.location.pathname , images:% 5B% 5D, imagesOnViewPort:% 5B% 5D, videos: document.querySelectorAll (% 22video% 22), regexOriginalImage: /% 5C /% 5Ba-z% 5D +% 5Cd +% 5Ba-z% 5D? x% 5Cd +% 5Ba-z% 5D? /, RegexMaxResImage: /% 5C /% 5Ba-z% 5D +% 5B1080% 5D +% 5Ba-z% 5D? X% 5B1080% 5D +% 5Ba-z% 5D? /, RegexPath: / % 5E% 5C / p% 5C //, regexHostname: /instagram%5C.com/,regexStoriesURI: / stories% 5C /(.*)+/, regexURL: / (% 5B -:% 5Cw? @% 25 & + ~% 23 =% 5D *% 5C.% 5Ba-z% 5D% 7B2,4% 7D% 5C /% 7B0,2% 7D) ((?:% 5B? &% 5D (?:% 5Cw +) = (?:% 5Cw +)) +% 7C% 5B -:% 5Cw? @% 25 & + ~% 23 =% 5D +)? /, FoundByModule: null, probablyHasAGallery:% 7Bcheck: null, byModule:% 22% 22% 7D, setImageLink: function (e)% 7Bthis.image LinkBeforeParse = e, this.regexMaxResImage.test (e)? This.imageLink = e: this.imageLink = this.regexOriginalImage.test (e)? E.replace (this.regexOriginalImage,% 22% 22): e% 7D, foundVideo:! 1, foundImage:! 1, imageLink:! 1, imageLinkBeforeParse:! 1, alertNotInInstagramPost:! 1, context:% 7BhasMsg:! 1, msg:% 22% 22% 7D% 7D, v = document.images; (0, r.default) (v, function (e, t)% 7B ((0, i.default) (t)% 7C% 7C2 === v.length) && (h.images.push (t) , (0, o.default) (t) && h.imagesOnViewPort.push (t))% 7D), h.regexHostname.test (h.hostname)% 7C% 7Cwindow.alert ((0, a.default) (% 22index @ alert_onlyWorks% 22)), h.regexHostname.test (h.hostname) && (! 1 === (0, s.default) (h) &&! 1 === (0, l.default) (h ) &&! 1 === (0, d.default) (h) &&! 1 === (0, u.default) (h) &&! 1 === (0, g.default) (h) && ! 1 === (0, m.default) (h) &&! 1 === (0, c.default) (h) && (h.context.hasMsg =! 1), h.context.hasMsg && window.alert ((0, a.default) (h.context.msg)) ,! h.alertNotInInstagramPost% 7C% 7Ch.foundVideo% 7C% 7Ch.foundImage% 7C% 7Cwindow.alert ((0, a.default) (% 22index % 23program @ alert_dontFound% 22)))% 7D, function (e, t, n)% 7B% 22use% 20strict% 22; Objec t.defineProperty (t,% 22__esModule% 22,% 7Bvalue:! 0% 7D); var% 20a = function (e)% 7Breturn% 20e && e .__ esModul "`

And then nothing happens anymore, the loading bar gets stuck

**Comment by saschaheim** [comment]
You can add instantgram to safari like this.
System: BigSur 11, Safari 14 should works also on lower versions
![Untitled](https://user-images.githubusercontent.com/16448231/104212366-72be3500-5435-11eb-910e-c432cf46d868.gif)

**Comment by UnixCro** [comment]
DUDE YOU ARE A GENIUS
