### ISSUE TITLE
Videos Not Working for me

### ISSUE THREAD

**Issue by M1kep** [theus/instantgram#4]
Whenever I attempt to use the tool on a video i'm given the following error:

![image](https://user-images.githubusercontent.com/2661819/38472058-e79c320a-3b2e-11e8-9869-9c7e5eb4e71a.png)

**Comment by M1kep** [comment]
Did some more testing in another browser and it seems to pull the thumbnail now as well

**Comment by theus** [comment]
Thanks for the issue. Well, Instagram changed the method that videos are requested on the page. I'll try to release a fix in the next major version (3) but if I can not resolve it, unfortunately [instantgram] will not get videos anymore.

**Comment by theus** [comment]
Hi @M1kep. Sorry for the late. More details at [release notes](https://github.com/theus/instantgram/releases/tag/v3.0.0)
