### ISSUE TITLE
Last image in posts on feed won't extract + a few other issues

### ISSUE THREAD

**Issue by nationali** [theus/instantgram#40]
I've been using this almost daily for image scraping since around version 3.0.0, and these are a few bugs I've noticed. Some have popped up more recently, some have been an issue for a while. (Thanks BTW theus, the bookmark has infinitely improved my workflow as opposed to when I had to inspect element everything.)

The first issue is pretty straight forward, but when you attempt to extract the last image in a post with multiple images, it will instead extract the image or video which came before it in the post. This is really only a mild annoyance as you're still able to pull it from inspecting it. This also only happens on the actual feed, when you actually go view the post through their profile it works fine. 

The second issue is the stories cropping issue from the other recently posted issue report. It's possible it may only be an issue for Firefox users, but I'm pretty sure it has more to do with the size of the source files being posted, as it only consistently happens to a few specific users for me. When you inspect element the story and hover over the image, it's full sized. But when you actually open the image using the URL, it's the cropped version. This one's slightly more annoying, as the only way to get the full sized image is by using some sort of story grabber site (like [this](https://www.instadp.com/download-instagram-stories) or [this](https://www.storysaver.net/)). I have no idea what they're doing on their end that solves the issue, but it's probably something to look into. 

Finally the last and most concerning issue, the one that prompted me to make this report, is the new stories layout. I saw in a previous report that you said you didn't have the new layout, but hopefully you'll have it soon so you can evaluate it for yourself, as this completely breaks using the bookmark for stories. You're essentially only able to pull the images from the first user in the stories feed. Once you move to the next user, you're unable to pull any images from their stories, and it will automatically attempt to pull the last image in a previous users story. However, even this doesn't work, as if none of the previous users have an image for their final story, it will simply open a page with a URL mismatch or the first frame of their video.

**Comment by theus** [comment]
Hey, can you check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
