### ISSUE TITLE
instagram home page error

### ISSUE THREAD

**Issue by ghost** [theus/instantgram#41]
**searchVideoInPage()** [instantgram] 4.0.3 _TypeError: n.querySelectorAll is not a function_
    at t.default (<anonymous>:1:11018)
    at Object.<anonymous> (<anonymous>:1:3076)
    at n (<anonymous>:1:123)
    at <anonymous>:1:915
    at <anonymous>:1:924
    at <anonymous>:1:19241

**Comment by theus** [comment]
Hey, can you check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
