### ISSUE TITLE
Invalid URL Signature

### ISSUE THREAD

**Issue by joewbrown** [theus/instantgram#5]
Using Instantgram on my recent post directs to a blank page with the text "Invalid URL Signature".

Post: https://www.instagram.com/p/BkC7Iuznjby/?taken-by=joewbrown
Instantgram result: https://scontent-lga3-1.cdninstagram.com/vp/38fe1b859f99f6b64ccc0739dc900b43/5BA4B8BC/t51.2885-15/e35/34174682_201610923798305_8986516405935407104_n.jpg

**Comment by joewbrown** [comment]
Lightning fast work! Thanks a bunch!

**Comment by theus** [comment]
Thank you! 
After your issue, I started testing the fix at [instantgram] 3 but the version 3 isn't ready, so I brought to v2
