### ISSUE TITLE
Unable to load video types (Stories/Posts) for saving

### ISSUE THREAD

**Issue by kitocole** [theus/instantgram#50]
When clicking the bookmarklet on a video, a new tab opens, and the video doesnt load.

Expected behavior: Video would load when using bookmark.

Browser: Chrome 90.0.4430.212

This is what I see: 
![image](https://user-images.githubusercontent.com/14023882/119241476-752f4a80-bb0b-11eb-8113-db379ab4b333.png)

It seems like 5% of videos work randomly. But the ones that do not work never work

**Comment by theus** [comment]
@kitocole Can you send me an example of a post in which this error is happening?

**Comment by kitocole** [comment]
Hi @theus,

For example: https://www.instagram.com/stories/the.nurse.sarah/2580105419091865502/

This is a story, but any video stories (especially longer) would result in the above screen

Thanks

**Comment by theus** [comment]
@kitocole but, except story, do you have any post link with this problem?
