### ISSUE TITLE
Bookmarklet not working

### ISSUE THREAD

**Issue by Tuwushar** [theus/instantgram#51]
When I click on bookmarklet nothing happens.

**Comment by theus** [comment]
Hi @Tuwushar. Can you send me a link to an Instagram post that this behavior is happening?

**Comment by Tuwushar** [comment]
Not working on any post. I keep clicking on instantgram bookmark and
nothing happens.

**Comment by theus** [comment]
@Tuwushar are you using version 4.0.5?

**Comment by Tuwushar** [comment]
Yes, I am!

**Comment by theus** [comment]
@Tuwushar can you open the browser console and click on [instantgram] bookmarklet? Check if something happens there.

**Comment by Tuwushar** [comment]
I have shared with you the screen recording. As you can see nothing happens
even if I click the bookmarklet.

**Comment by theus** [comment]
> I have shared with you the screen recording. As you can see nothing happens even if I click the bookmarklet.

Did you share?

**Comment by Tuwushar** [comment]
Shared in this one. As you can see nothing happens when I click the
bookmarklet.

**Comment by theus** [comment]
Hey, can you check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
