### ISSUE TITLE
Videos & Reels not working

### ISSUE THREAD

**Issue by Kerslake14** [theus/instantgram#52]
When i go to a video or reel and click on the bookmark nothing happens.

See screen recording attached.

https://user-images.githubusercontent.com/90785692/133466927-ac674dbd-d976-48f2-b615-bba02c742f79.mov

**Comment by theus** [comment]
Hey, can you check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
