### ISSUE TITLE
Not working on posts with non-responsive images

### ISSUE THREAD

**Issue by abrwright** [theus/instantgram#53]
I’m increasingly encountering Instagram posts serving up non-responsive `img` tags where the image element includes only a `src` attribute, with no `srcset` attribute.

Compare these two posts: https://www.instagram.com/p/CU2EYSjtTKN/ and https://www.instagram.com/p/CU0WiSkpL_9/

The markup for the first includes both `src` and `srcset` attributes, the second only `src`. The bookmarklet only works for me on the first.

**Comment by onmyouji** [comment]
> I’m increasingly encountering Instagram posts serving up non-responsive `img` tags where the image element includes only a `src` attribute, with no `srcset` attribute.
> 
> Compare these two posts: https://www.instagram.com/p/CU2EYSjtTKN/ and https://www.instagram.com/p/CU0WiSkpL_9/
> 
> The markup for the first includes both `src` and `srcset` attributes, the second only `src`. The bookmarklet only works for me on the first.

Hey, seems like they did some changes on the website. Now the bookmarklet works on the second image. Last week it also didn't work for me.

**Comment by theus** [comment]
Hey, can you all check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
