### ISSUE TITLE
Only pulling first image in post.

### ISSUE THREAD

**Issue by runchbox** [theus/instantgram#54]
Hi, it is getting the first image from a post with multiple images but not any others.
I haven't tried with multiple videos yet.

This is only since the new IG update.

**Comment by theus** [comment]
Thanks for issue. I'll take a look.

**Comment by barn** [comment]
on Chrome 97 I get the following on the console when trying the second image in a set. The first one works just fine though.

```
VM14244:1 searchVideoInModalPost() [instantgram] 4.0.5 TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at e.execute (<anonymous>:1:11504)
    at Module.<anonymous> (<anonymous>:1:16443)
    at n (<anonymous>:1:123)
    at <anonymous>:1:915
    at <anonymous>:1:924
    at <anonymous>:1:16712
VM14244:1 searchImageInModalPost() [instantgram] 4.0.5 TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at e.execute (<anonymous>:1:14435)
    at Module.<anonymous> (<anonymous>:1:16493)
    at n (<anonymous>:1:123)
    at <anonymous>:1:915
    at <anonymous>:1:924
    at <anonymous>:1:16712
VM14244:1 searchImageInPage() [instantgram] 4.0.5 TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at e.execute (<anonymous>:1:12258)
    at Module.<anonymous> (<anonymous>:1:16518)
    at n (<anonymous>:1:123)
    at <anonymous>:1:915
    at <anonymous>:1:924
    at <anonymous>:1:16712
```

which looking at ImageInModalPost is hitting https://github.com/theus/instantgram/blob/gh-pages/src/modules/ImageInModalPost.ts#L35 as, for me, `liElements.length == 4`

Which I'm guessing by the commented out `console.log` means this isn't an entirely unknown outcome, just not the right one.

**Comment by theus** [comment]
I think some update on Instagram changed the internal structure. I'll check.

**Comment by theus** [comment]
Hey, can you all check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
