### ISSUE TITLE
Stories on Safari result in an image, not video. Works in Firefox.

### ISSUE THREAD

**Issue by A-0-0-P** [theus/instantgram#55]
When using the bookmarklet in Safari 15.1 (but also 15.0) on a story I just get the still image of that video. When I do the same in Firefox (93) I get the video.

Catalina 10.15.7

**Comment by theus** [comment]
Safari is more complicated to test, but I'll try to look to this issue.

**Comment by theus** [comment]
Hey, can you check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
