### ISSUE TITLE
Not working anymore on Chrome

### ISSUE THREAD

**Issue by Timelessprod** [theus/instantgram#57]
Hi,

The extension does not work anymore : nothing happens when clicking on it when being on an instagram post.

**Comment by irrg** [comment]
Same on Safari. Looks like instagram changed their markup and one of the querySelectors is failing:

```
[Error] searchImageInPage() – "[instantgram] 4.0.5"
TypeError: undefined is not an object (evaluating 'n[0].querySelectorAll')
(anonymous function) — CZIBQ8qPh8Q:1:12258
(anonymous function) — CZIBQ8qPh8Q:1:16526
n — CZIBQ8qPh8Q:1:128
(anonymous function) — CZIBQ8qPh8Q:1:917
(anonymous function) — CZIBQ8qPh8Q:1:925
Global Code — CZIBQ8qPh8Q:1:16713
	(anonymous function) (Script Element 4:1:12826)
	(anonymous function) (Script Element 4:1:16526)
	n (Script Element 4:1:128)
	(anonymous function) (Script Element 4:1:917)
	(anonymous function) (Script Element 4:1:925)
	Global Code (Script Element 4:1:16713)
```

**Comment by irrg** [comment]
Instagram might have reverted something they changed? It's working again for me. EDIT: on one, of two, identical laptops, with identical OSes and identical browsers, it's working correctly. On the other, this error. A/B testing?

**Comment by theus** [comment]
Instagram changed something in their code. I need to review [instantgram] system.

**Comment by klayhb** [comment]
it's weird, acting inconsistently - sometimes it works on all images in a post, other times it only works on some.
For stories - it almost always works for videos but almost never works for images

**Comment by theus** [comment]
Hey, can you all check if [v4.0.7](https://github.com/theus/instantgram/releases/tag/v4.0.7) did fix that?
