### ISSUE TITLE
Unable to "Instantgram" extra photos multiple photo posts.

### ISSUE THREAD

**Issue by AdamKnowlesy** [theus/instantgram#6]
With the feature to add more than one to photo to a post on Instagram, it seems that no matter which photo i choose in the post it always defaults either to the first photo in the post, or randomly the second photo in the post, I can never seem to get further.

**Comment by theus** [comment]
@AdamKnowlesy thanks for the issue. I think it's solved now.

**Comment by AdamKnowlesy** [comment]
@theus It certainly is, thank you for your super quick support! :)

**Comment by theus** [comment]
@AdamKnowlesy thanks =). I'm slowly developing the version 3, so I'll replicate the bug fix to the next version. Btw, it's not a big deal. The bad of the currently version is the build system, appear random bugs and it's so boring. At least I hope to solve in the next one.
