### ISSUE TITLE
Image in album will not open if next(or previous) in album is a video

### ISSUE THREAD

**Issue by kitocole** [theus/instantgram#69]
Steps:
1. Find album post where an image comes right before or right after a video
2. Navigate to the image right before/after the video
3. Use the bookmarklet.

Expected:
- The image would appear in new tab

Actual:
- The video is opened in a new tab.

This occurs both on the user's profile and on the album page itself.

**Comment by slomomojo** [comment]
Same issue as described in #62.

**Comment by kitocole** [comment]
any update?

**Comment by mklaber** [comment]
I believe I've fixed this in https://github.com/theus/instantgram-core/pull/2 but if you can post an example URL where you're seeing this I can confirm (even before @theus releases my fixes).

**Comment by slomomojo** [comment]
Test links from #62 : 
https://www.instagram.com/p/CcYAQmnuuEY/
https://www.instagram.com/p/CXcBUbNhNef/

**Comment by mklaber** [comment]
The first link (https://www.instagram.com/p/CcYAQmnuuEY/) works with my fix but it also doesn't have an image so it's probably not reflective of the problem described in the ticket.

However, the second link still does not work.

I believe I've fixed it and it'll be made available when @theus merges it.

**Comment by theus** [comment]
Merged! Thanks @mklaber 🎉

**Comment by slomomojo** [comment]
Thanks for the fix.  All seems good now.
