### ISSUE TITLE
Invalid URL signature

### ISSUE THREAD

**Issue by MacDogg** [theus/instantgram#7]
Thanks for the great tool.  Recently started getting an error.
On Thursday night I received the message about an update so I deleted the old bookmark and added the new one.  Using Firefox Quantum 61.0.1 on Windows 10:
Login to Instagram.com, go to any persons page (https://www.instagram.com/therock/), click on a pic in his grid, click the bookmark, receive Invalid URL signature message.
If I am on the main Instagram page and scrolling down the list of pictures from people I follow the bookmark works properly and I get a full size pic.  It only gives the invalid signature error when I go directly to a persons page, scroll through their pics, click on one and then use the bookmark.

**Comment by Dyras** [comment]
Here's how to reproduce:
Click this: https://www.instagram.com/jodellemicah/
Press seemingly any image
Press the bookmark
URL signature mismatch

**Comment by niallone** [comment]
I'm having the same issue, looks like they're signing the url to prevent outside access..

**Comment by theus** [comment]
Thanks @MacDogg for the issue and @Dyras for the steps to reproduce. I'll investigate this.

**Comment by theus** [comment]
I fixed the bug using @Dyras steps to reproduce. I thinks is right now. More details at [release](https://github.com/theus/instantgram/releases/tag/v3.0.0)

**Comment by MacDogg** [comment]
Thanks for the fast response.  I have confirmed this is working for me now!!
