### ISSUE TITLE
first and last pictures in carousel won't open

### ISSUE THREAD

**Issue by another-juan** [theus/instantgram#72]
the first and last pictures in any post where there's more than one -like [this one](https://www.instagram.com/p/CZf0ZOipC_H)- don't open, or produce any error message (still, the right links are stored on p as i[0].src for the first one, and i[1].src for the last)
i remember the issue happening randomly before, but it became consistent since a few days ago. version 5.0.1, chrome 106, windows 10, from colombia. thanks for your cool and useful script, btw

**Comment by Scontoni** [comment]
I have been having the same issue with Opera 90.0.4480.84 on Win11
