### ISSUE TITLE
Bookmarklet doesn't work with opening Instagram stories

### ISSUE THREAD

**Issue by AnimeGeekDraws** [theus/instantgram#75]
While the update is finally able to open posts with more than one pic, it is still unable to open up Instagram stories because every time I do, it always gives me a different photo.

**Comment by TampaPixx** [comment]
Getting the same now.  Used to work for the videos in Stories/Highlights in 5.0.1. about two weeks ago.  Now doesn't work in 5.0.1 or 5.0.2.  Instagram has changed something now results in a random jpg.

**Comment by Wag669** [comment]
> Getting the same now. Used to work for the videos in Stories/Highlights in 5.0.1. about two weeks ago. Now doesn't work in 5.0.1 or 5.0.2. Instagram has changed something now results in a random jpg.

I can confirm same behavior with 5.0.2 on FF

**Comment by mklaber** [comment]
@theus looks like they started doing stories as `blob:`, I haven't had time to see if an MP4 is in the rx metadata. The selector also is no longer `video > source`. 

The photo that it "finds" is the user's profile photo.

I'll try to look more at it this weekend.

**Comment by TampaPixx** [comment]
You sir, are a WIZARD!  Thanks so much for getting this done.

Dan Perez

www.tampapix.com <http://www.tampapix.com>

**Comment by TampaPixx** [comment]
Hello, Matheus,

I’m not sure if this is the proper way of contact, so please excuse if there is a better way.  I was on your page at GitHub but do not find a contact method.  Please also excuse me as this field of knowledge is WAY beyond my capacity to grasp.  I only use Instagram to save photos and videos which my daughter posts on Instagram during her travels in Europe for some months now.  I have saved nearly 600 photos thanks to your ingenious creation.  Also very many videos as Instantgram worked for videos too.

 

But my purpose for this contact is only to let you know that now videos do not download with audio.  They are all silent. I tried with Edge browser and Chrome browser.  I suppose Instantgram wasn’t intended to save videos, but if there is a fix or a method for me to search the source code for the video with audio URL, I have a little experience doing that.

 

Thank you so much for your fine work!

Dan Perez

TampaPix.com
