### ISSUE TITLE
Open videos instead of the picture in 5.0.4

### ISSUE THREAD

**Issue by Rocket3192** [theus/instantgram#79]
Hello, in version 5.0.4, we can't open a picture if the very next or the very previous content is a video, it will open the video instead

For example if you have an insta post containing 5 pics and a single video (so 6 contents in total)

If the video is on 3rd place, you can't open the 2nd picture neither you can open the 4th one, both will open the video, you can still open the 1st, 5th and 6th pictures

For
P = picture
V = video

 P    P   V   P   P   P 
✔❌⭕️❌✔✔

 P   P   P   P   V   P
✔✔✔❌⭕️❌

I think there is another problem when there are multiple videos, like a video will open instead of another one

By the way I'm using the last version of Edge (chromium)

**Comment by theus** [comment]
Hey, can you provide a post link as an example?

**Comment by Rocket3192** [comment]
> Hey, can you provide a post link as an example?

For example : https://www.instagram.com/p/ClXFS-Vp4CV/
If you try to open the second picture, it will open the first video, 3rd picture will open the 4th video same for 5th picture, 6th and 8th pictures will open 7th video, 9th and 10th pictures work fine

**Comment by Rocket3192** [comment]
Maybe a hint to find the reason, I figured when there is at least a certain number of pictures / videos in a post, the extension make it so it shows the second post for example on this : https://www.instagram.com/p/CocxUAiozUt/
It opens on the second picture : 
![image](https://user-images.githubusercontent.com/123319690/218080811-e96adb27-ed1a-47d9-aae7-ea3fab9f5859.png)

I don't know if that's related to the problem

**Comment by Rocket3192** [comment]
Hey, any update on that matter ? 

Thank you :)

**Comment by Rocket3192** [comment]
Well I just tried this one : [redacted]
And it fixes the problem

**Comment by theus** [comment]
@Rocket3192 sorry, I just removed the link since this repo stole the code of [instantgram]
