### ISSUE TITLE
Does nothing in Safari

### ISSUE THREAD

**Issue by Stokestack** [theus/instantgram#85]
Clicking on the Instantgram entry in the bookmarks bar has no effect.

On a side note: It does work in Brave.

**Comment by theus** [comment]
Do you have a screenshot of the error?

**Comment by Stokestack** [comment]
Thanks for the follow-up. Just tried it again, and it works fine in Safari. No idea what was going on before. Maybe just a coincidental Safari failure; it has a longstanding defect where it gets into a state that doesn't respond to clicks or user actions.
