### ISSUE TITLE
Video Issue

### ISSUE THREAD

**Issue by AnimeGeekDraws** [theus/instantgram#87]
Apparently, I am still having an issue with opening videos as of today. Yes I keep refreshing the post, but for some reason today, refreshing the post and opening the video, the video has no audio.

**Comment by TampaPixx** [comment]
Having same issue, videos used to dowlnload with audio, now audio is missing.  I tried searching the code but it's all Greek to me. WAY over my head!

**Comment by theus** [comment]
I'm afraid that I can do anything related to audios, since that is an Instagram limitation :/

**Comment by theus** [comment]
Related: https://github.com/theus/instantgram/issues/78

**Comment by TampaPixx** [comment]
Thanks, Matheus.  I have found a solution, it’s a bit time-consuming, but it works..

 

First add this to end of the Instagram  video URL as it is playing.  Make sure the sound is on:

?__a=1&__d=dis

 

Then search (CtrlF) that page full of code for this:

video_versions

 

Follow that line of code until you see the first instance of "https://scontent-ord5-1.cdninstagram.com  (there may be more than one instance, so use the first one that occurs.)

This is the beginning of a very long URL of the video.

 

Copy the text from after that first quote mark (start with https:) to before the next quote mark.  It will be several lines, a very long URL.

 

Paste that URL in your address bar and GO!

 

The video is now playing from the actual original URL so just right click and save video as.

 

EXAMPLE OF WHAT THE URL WOULD APPEAR LIKE:

 

[{"type":101,"width":1080,"height":1920,"url":"https://scontent-ord5-1.cdninstagram.com/o1/v/t16/f1/m82/B649xxxxxxxxxx05F5F5BB_video_dashinit.mp4?efg=eyJxZV9ncm91cxxxxxxxxxxGVsaXZlcnlfdnRzX290ZlwiXSIsInZlbmNvZGVfdGFnIjoidnRzX3ZvZF91cmxnZW4uNzIwLmNsaXBzLmJhc2VsaW5lIn0&_nc_ht=scontent-ord5-1.cdninstagram.com&_nc_cat=108&vs=120966xxxxxxx53549_473925628&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC9CNjQ5QzgwODNBODlENjFDMkM1RkQ0RDkwNUY1RjVCQl92aWRlb19kYXNoaW5pdC5tcDQVxxxxxxxxxbjdCUG1wY0NxRFN3Q0FIS0xESVpJdVEwQ2JxX0VBQUxxxxxxxxxxxxxQAAJpzDrZ6lk9g%2FFQIoAkMzLBdALaXXXXXXXXXXXXXXXXXXXXXXXXp%2B%2Bdsi0RgSZGFzaF9iYXxxxxxxxxxEQB1%2FgcA&_nc_rid=85b68b47f0&ccb=9-4&oh=00_AfCHCfg3tgP89fDSwbs0ya4cahSvHuLxKDc_RjNurgQ0ww&oe=64EC4E24&_nc_sid=4f4799","id":"254494697502593v"},{"type":
