### ISSUE TITLE
Doesn't work on highlights

### ISSUE THREAD

**Issue by Rocket3192** [theus/instantgram#92]
Hey, the script doesn't work on hightlights stories ( /stories/highlights/ ) 

ImageVideoInStories() [instantgram] 5.0.5 TypeError: Cannot read properties of null (reading 'querySelector')
    at t.execute (<anonymous>:1:4142)
    at Module.<anonymous> (<anonymous>:1:15213)
    at n (<anonymous>:1:123)
    at <anonymous>:1:915
    at <anonymous>:1:924
    at <anonymous>:1:15481
e.error @ VM527:1
t.execute @ VM527:1
(anonymous) @ VM527:1
n @ VM527:1
(anonymous) @ VM527:1
(anonymous) @ VM527:1
(anonymous) @ VM527:1

**Comment by theus** [comment]
Hey 👋 ,

Which profile are you getting that error? Just tested with https://www.instagram.com/spotify/ and it worked fine

**Comment by theus** [comment]
The [v5.0.6](https://github.com/theus/instantgram/releases/tag/v5.0.6) version can solve that issue 🤔

**Comment by Rocket3192** [comment]
Thanks, with 5.0.6 we can now have the highlights but there is still a problem, this is only video, there is no audio :)
tested on Spotify aswell
This is still an upgrade
