### ISSUE TITLE
Problemas com muitos stories (Sem título) e (about:blank) na URL. 

### ISSUE THREAD

**Issue by desbravadordemundos** [theus/instantgram#93]
Tá dando o erro "sem título" em muitos stories que tento baixar, as vezes atualizo a página e ele consegue baixar, mas na maioria das vezes não funciona.

**Comment by theus** [comment]
Qual perfil? Pode mandar o link?

**Comment by theus** [comment]
A versão [v5.0.6](https://github.com/theus/instantgram/releases/tag/v5.0.6) pode resolver isso
